config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index]
  resources :posts, only: [:index]
  resources :trends, only: [:index]
  resources :influencers, only: [:index]

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/influencers_controller.rb
class InfluencersController < ApplicationController
    def index

        users = HTTParty.get('https://jsonplaceholder.typicode.com/users')
    
        @influencers = []
    
        users.each do |user|
          hash = Hash.new
          
          iduser = user["id"].to_s
          
          postsuser = HTTParty.get('https://jsonplaceholder.typicode.com/users/'+ iduser +'/posts')
          
          nposts = 0
          ncomtarios = 0
          
          postsuser.each do |postuser|
    
            idpost = postuser["id"].to_s
            comentariosposts = HTTParty.get("https://jsonplaceholder.typicode.com/posts/"+ idpost +"/comments")
            
    
            comentariosposts.each do |count|
              ncomtarios += 1
            end
    
            nposts += 1
            
          end
          
          hash["name"] = user["name"]
          hash["indiceP"] = ncomtarios.to_i/nposts.to_i
    
          @influencers.push(hash)
    
        end
    
    
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        posts = HTTParty.get('https://jsonplaceholder.typicode.com/posts')
    
        @postsfiltrados = []
    
        posts.each do |post|
          hash = Hash.new
    
          hash["title"] = post["title"]
          hash["body"] = post["body"]
    
          usuariopost = HTTParty.get('https://jsonplaceholder.typicode.com/users/'+ post["userId"].to_s)
          hash["name"] = usuariopost["name"]
    
          idpost = post["id"].to_s
          comentariosposts = HTTParty.get("https://jsonplaceholder.typicode.com/posts/"+ idpost +"/comments")
          ncomentarios = 0 
          comentariosindex = []
    
          comentariosposts.each do |key, value|
            hascomentario = Hash.new
            hascomentario["comentario"] = key["body"]
            comentariosindex.push(hascomentario)
          end
    
          comentariosposts.each do |count|
            ncomentarios += 1
          end
    
          hash["total"] = ncomentarios.to_s
          hash["comentarios"] = comentariosindex
    
          @postsfiltrados.push(hash)
    
    
        end
        
    end
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
    def index
        @postordenados = []


        posts = HTTParty.get('https://jsonplaceholder.typicode.com/posts')


        posts.each do |post|

        idpost = post["id"].to_s
            
        hash = Hash.new
        user = HTTParty.get('https://jsonplaceholder.typicode.com/users/'+ post["userId"].to_s)
        comentariosposts = HTTParty.get("https://jsonplaceholder.typicode.com/posts/"+ idpost +"/comments")

        ncomtarios = 0 
        comentariosposts.each do |count|
            ncomtarios += 1
        end
     
        
        iduser = user["id"].to_s
        
        hash["name"] = user["name"]
        hash["title"] = post["title"]
        hash["body"] = post["body"]
        hash["total"] = ncomtarios.to_s

        @postordenados.push(hash)
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      
        users = HTTParty.get('https://jsonplaceholder.typicode.com/users')
    
        @userlist = []
    
        users.each do |user|
    
          hash = Hash.new
    
          iduser = user["id"].to_s
          postsuser = HTTParty.get('https://jsonplaceholder.typicode.com/users/'+ iduser +'/posts')
          nposts = 0
    
          postsuser.each do |count|
            nposts += 1
          end
    
          hash["name"] = user["name"]
          hash["username"] = user["username"]
          hash["email"] = user["email"]
          hash["address"]= user["address"]
          hash["phone"] = user["phone"]
          hash["website"] = user["website"]
          hash["company"] = user["company"]
          hash["nposts"] = nposts.to_s
    
          @userlist.push(hash)
        
        
        end
    
    
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/influencers_helper.rb
module InfluencersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/trends_helper.rb
module TrendsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/influencers/index.html.erb
<div class="container">
    <table id="myTable" class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Indice de popularidad</th>
            </tr>
        </thead>
        <tbody>
            <% @influencers.each do |user| %>
            <tr>
                <td><%= user["name"] %></td>
                <td><%= user["indiceP"] %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>
<script type="text/javascript">
    $('#myTable').DataTable({
    "lengthMenu": [5]}); // se setean 5 entradas, pero se dejan los demás usuarios para poder filtrar
                        //según estime el usuario final, por si se requieren medir otras metricas
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WapiiNet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item nav-link">
          <%= link_to 'Usuarios', users_path %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to 'Publicaciones', posts_path %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to 'Tendencia', trends_path %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to 'Influencers', influencers_path %>
        </li>
        
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container">
    <div class="container">
    <table id="myTable" class="table">
        <thead>
            <tr>
                <th>Autor</th>
                <th>Título</th>
                <th>Texto</th>
                <th>Comentarios</th>
                <th>Total comentarios</th>
            </tr>
        </thead>
        <tbody>
            <% @postsfiltrados.each do |post| %>
            <tr>
                <td><%= post["name"] %></td>
                <td><%= post["title"] %></td>
                <td><%= post["body"] %></td>
                
                <td>
                    <ul>
                        <li><%= post["comentarios"][0]["comentario"] %></li>
                        <li><%= post["comentarios"][1]["comentario"] %></li>
                        <li><%= post["comentarios"][2]["comentario"] %></li>
                    </ul>    
                </td>
                <td><%= post["total"] %></td>

            </tr>
            <% end %>
        </tbody>
    </table>

<script type="text/javascript">
    $('#myTable').DataTable();
</script>

app/views/trends/index.html.erb
<div class="container">
    <div class="container">
    <table id="myTable" class="table">
        <thead>
            <tr>
                <th>Autor</th>
                <th>Título</th>
                <th>Texto</th>
                <th>Total comentarios</th>
            </tr>
        </thead>
        <tbody>
            <% @postordenados.each do |post| %>
            <tr>
                <td><%= post["name"] %></td>
                <td><%= post["title"] %></td>
                <td><%= post["body"] %></td>
                <td><%= post["total"] %></td> <!--se añade indicador para saber cuantos comentarios tiene en cantidad 
                                                    y aprvechar de mejor manera el filtro que viene en datatable-->
            </tr>
            <% end %>
        </tbody>
    </table>

<script type="text/javascript">
    $('#myTable').DataTable({
    "lengthMenu": [10, 25, 50]}); //se puede setear a los n elementos que quieras
</script>

app/views/users/index.html.erb
<div class="container">
    <table id="myTable" class="table">
        <thead>
            <tr>
                <th>Nombre Usuario</th>
                <th>Cantidad de pubilcaciones</th>
            </tr>
        </thead>
        <tbody>
            <% @userlist.each do |user| %>
            <tr>
                <td><%= user["name"] %></td>
                <td><%= user["nposts"] %></td>


            </tr>
            <% end %>
        </tbody>
    </table>
</div>
<script type="text/javascript">
    $('#myTable').DataTable();
</script>